### ISSUE TITLE
When included in client side scripting

### ISSUE THREAD

**Issue by jrahulroy** [Kibo/numbers2words#1]
module variable throws an error when included in client side at following line at the end of document

``` javascript
// Node exports
if(module.exports){
    module.exports = T2W;
}
```

Updated the above as

``` javascript
// Node exports
if (typeof(module) !== 'undefined' && module.exports) {
    module.exports = T2W;
}
```

**Comment by Kibo** [comment]
Fixed by [Kulor](https://github.com/kulor)
https://github.com/Kibo/numbers2words/pull/3
